config/routes.rb
HapGc::Application.routes.draw do
  get "profiles/show"

  devise_for :users
  resources :pins
  get 'board', to: 'pins#index', as: :board
  root :to => 'pins#index'

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  get '/:id', to: 'profiles#show'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	attr_accessible :category, :name, :address, :latitude, :longitude, :gmaps, :date, :time, :desc, :user_id;
	belongs_to :user

	validates :category, presence: true
	validates :name, presence: true,
	                 length: { minimum: 2, maximim: 200}
	validates :address, presence: true,
	                 length: { minimum: 2, maximim: 200}
	validates :date, presence: true
	validates :time, presence: true
	validates :desc, presence: true,
	                 length: { minimum: 2, maximim: 2000}

	validates :user_id, presence: true

	#geocoded_by :address
	#after_validation :geocode, :if => :address_changed?

	acts_as_gmappable

	def gmaps4rails_address
	  address
	end

	def desc_short
		desc[0..199] + "..."
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :profile_name, :email, :password, :password_confirmation, :remember_me

  validates :first_name, presence:true
  validates :last_name, presence:true
  validates :profile_name, presence:true, 
                           uniqueness:true, 
                           format: { 
                            with: /^[a-zA-Z0-9][a-zA-Z0-9_-]*$/,
                            message: 'must be formatted correctly. (No spaces or crazy characters)'
                           }

  has_many :pins

  def full_name
  	first_name + " " + last_name
  end
  
  def gravurl
    clean_email = email.strip.downcase
    hash = Digest::MD5.hexdigest(clean_email)
    "http://gravatar.com/avatar/#{hash}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
    @json = Pin.all.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end
  
  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = Pin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = Pin.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = Pin.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@pins = @user.pins.all
  		render action: :show
  	else
	  	render file: 'public/404', status: 404, formats: [:html]
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"		
		else
			""
		end
	end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Happining Dev</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="robots" content="noindex, nofollow">
</head>
<body>
	<div id="banner">
		<h1 id="logo" class="left"><%= link_to 'Happining', root_url %></h1>
		
		<ul id="nav" class="right">
			<% if user_signed_in? %>
				<li><%= link_to current_user.profile_name, edit_user_registration_path %></li>
				<li><%= link_to "Logout", logout_path %></li>
			<% else %>
				<li><%= link_to "Register", register_path %></li>
				<li><%= link_to "Login", login_path %></li>
			<% end %>
		</ul>
	</div>
	<% flash.each do |type, message| %>
		<div class="alert <%= flash_class type %>">
			<button class="close" data-dismiss="alert">x</button>
			<%= message %>
		</div>
	<% end %>
	<%= yield %>
	<%= yield :scripts %>
</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h3><%= pluralize(@pin.errors.count, "fup") %>:</h3>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td><h4><%= f.label :category %></h4></td>
      <td><%= f.select :category, options_for_select([["Select Category", ""],"Event", "Job/Project", "Product"]) %></td>
    </tr>
    <tr>
      <td><h4><%= f.label :name %></h4></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><h4><%= f.label :address %></h4></td>
      <td><%= f.text_field :address %></td>
    </tr>
    <tr>
      <td><h4><%= f.label :date %></h4></td>
      <td><%= f.date_select :date %></td>
    </tr>
    <tr>
      <td><h4><%= f.label :time %></h4></td>
      <td><%= f.time_select :time %></td>
    </tr>
    <tr>
      <td colspan="2">
        <h4><%= f.label 'Description' %></h4>
        <%= f.text_area :desc %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
    <h5>Pinned by: <%= f.input :user_id, collection: User.all, label_method: :profile_name %></h5></h4></td>
    </tr>
    <tr>
      <td colspan="2" class="pin-cont">
        <%= link_to 'Cancel', root_url %> <%= f.submit 'Pin It', :class => 'btn' %>
      </td>
    </tr>
  </table>
<% end %>

app/views/pins/edit.html.erb
<% if user_signed_in? %>

<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', root_url %>
<% else %>
	<h1>You need to sign in.</h1>
<% end %>

app/views/pins/index.html.erb
<div class="cont">


</div>   

<table id="board-table">
    <tr id="board-cont">
        <td>   
            <!--<<%#= form_tag pins_path, :method => :get do %>
                <%#= text_field_tag :search, params[:search] %>
                <%#= submit_tag "Search Near", :name => nil %>
            <%# end %>-->
        </td>
        <td id="new-pin">
            <% if user_signed_in? %>
                <%= link_to 'New Pin', new_pin_path, :class => 'btn' %></td>
            <% end %>
    </tr>
    <tr>
        <td id="board">
            <%= gmaps4rails(@json) %>
        </td>
        <td id="flow">
            <% @pins.each do |pin| %>
                <div class="pin">
                    <h3><%= link_to pin.name, pin %></h3>
                    <h4><%= pin.address %></h4>
                    <h4><%= pin.date.strftime("%B %d, %Y") %> <%= pin.time.strftime("%H:%M") %></h4>
                    <p><%= pin.desc_short %></p>
                    <h4 style="text-align:right;"><%= pin.user.profile_name %><%= image_tag pin.user.gravurl %></h4>

                    <!--<#% if user_signed_in? %>
                    <p>
                        <#%= link_to 'Edit', edit_pin_path(pin) %> |
                        <#%= link_to 'Delete', pin, confirm: 'Are you sure?', method: :delete %>
                    </p>
                    <#% end %>-->
                </div>
            <% end %>
        </td>
    </tr>
</table>

app/views/pins/new.html.erb
<% if user_signed_in? %>
	<div>
		<h1>Create a Pin</h1>
		<%= render 'form' %>
	</div>
<% else %>
	<h1>You need to sign in.</h1>
<% end %>

app/views/pins/show.html.erb
<form><div>
    <h3><%= link_to @pin.name, @pin %></h3>
    <h4><%= @pin.address %></h4>
    <p><%= @pin.latitude %>, <%= @pin.longitude %></p>
    <h4><%= @pin.date.strftime("%B %d, %Y") %> <%= @pin.time.strftime("%H:%M") %></h4>
    <p><%= @pin.desc %></p>
    <h5>Pinned by: <%= @pin.user.profile_name %></h5>
</div>
<div>
	<p>
		<%= link_to 'Edit', edit_pin_path(@pin) %> |
		<%= link_to 'Continue', root_url %>
	</p>
</div>
</form>

app/views/profiles/show.html.erb
<div class="header">
	<h1><%= @user.profile_name %></h1>
</div>
<div id="flow">
	<% if @pins %>
		<% @pins.each do |pin| %>
			<div class="pin">
		        <h3><%= link_to pin.name, pin %></h3>
		        <h4><%= pin.address %></h4>
		        <h4><%= pin.date.strftime("%B %d, %Y") %> <%= pin.time.strftime("%H:%M") %></h4>
		        <p><%= pin.desc_short %></p>
			</div>
		<% end %>
	<% end %>
</div>